source 'https://supermarket.chef.io'

# Local cookbooks
cookbook 'system', path: '../system'
cookbook 'jb_spec', path: '../jb_spec'

cookbook 'ks_docker', path: '../ks_docker'
cookbook 'virtualbox', path: '../virtualbox'

cookbook 'sublime', path: '../sublime'
cookbook 'enpass', path: '../enpass'
cookbook 'monitoring', path: '../monitoring'

metadata
