name 'devSetup'
maintainer 'Jonathan Beckman'
maintainer_email 'jonathantbeckman@gmail.com'
description 'Installs/Configures an environment for developers'
long_description 'Installs/Configures an environment for developers'
version '0.1.0'

depends 'system', '~> 0.1.0'
depends 'jb_spec', '~> 0.1.0'

depends 'git', '~> 9.0.0'
depends 'java', '~> 2.0.1'
# depends 'dart', '~> 0.1.0'
depends 'maven', '~> 5.1.0'
# depends 'ks_docker', '~> 0.1.0'
depends 'virtualbox', '~> 0.1.0'
depends 'nodejs', '~> 5.0.0'

depends 'idea', '~> 0.6.0'
depends 'chrome', '~> 4.0.2'
depends 'sublime', '~> 0.1.0'
depends 'enpass', '~> 0.1.0'
depends 'monitoring', '~> 0.1.0'
